[project]
name = "genji"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "datapane>=0.17.0",
    "duckdb>=1.1.2",
    "fugashi>=1.3.3",
    "matplotlib>=3.9.2",
    "numpy>=2.0.2",
    "pandas>=1.5.3",
    "pyvis>=0.3.2",
]
